### ISSUE TITLE
feature request: show most recent steps on the left hand side

### ISSUE THREAD

**Issue by PFC-developer** [QuokkaStake/tmtop#24]
feature request: show most recent steps on the left hand side

**Comment by freak12techno** [comment]
@PFC-developer can you elaborate on what do you mean by that?

**Comment by PFC-developer** [comment]
so when you press the 'tab' button the rounds go from left to right, with new rounds being created off the page potentially.
I'd like the new rounds to be on the left hand side.

ie.
```
validator | round n | round n-1 | round n-2
```
instead of 
```
validator | round 0 | round 1 | ...
```

**Comment by freak12techno** [comment]
@PFC-developer ah, so basically invert rounds horizontally?

**Comment by PFC-developer** [comment]
yep

**Comment by freak12techno** [comment]
Makes sense. As of now, tmtop has this feature on the latest round mode, when you press T, it'd transpose the validators list so they'd fill columns first instead of rows. I was thinking of using the same hotkey to switch. Do you think that this would be nice?
Also, thanks for raising this, I already can see a case where this might be useful.

**Comment by freak12techno** [comment]
@PFC-developer can you check the linked PR and verify if it works for you? (still need to add help/readme entries, but the main job should be done)
basically, build from branch, press Tab to enter the all rounds mode, press T to transpose

**Comment by PFC-developer** [comment]
looks good.
